server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8081
  servlet:
    context-path: /emos-wx-api
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://175.178.13.217:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: Zz88921288
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: 17773124655@163.com
    password: UGODJKOMNUMGVOQQ

  redis:
    database: 0
    host: 175.178.13.217
    port: 6379
    password: Zz88921288
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: 175.178.13.217
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abc123456
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback.xml
#  level:
#    root: info
#    com.example.emos.wx.db.mapper : warn
#    org.springframework.data.convert.CustomConversions: ERROR

#  pattern:
#    console: "%d{HH:mm:ss}  %-5level  %msg%n"
emos:
  jwt:
    #密钥
    secret: abc123456
    #令牌过期时间（天）
    expire:  5
    #令牌缓存时间（天数）
    cache-expire: 10
  face:
    createFaceModelUrl: http://175.178.13.217:3000/create_face_model
    checkinUrl: http://175.178.13.217:3000/checkin
  email:
    system: 598523920@qq.com
    csadress: 17773124655@163.com
#  image-folder: E:/study/emos/image
  info-addrees: http://61.184.33.38:8081/GovEngine_GA_DCHY/aplanmis-rest/multiMeasure/getToken,http://218.200.85.171:9091/GovEngine_JM_DCHY/ehb/dataQuery/getToken
  image-folder: /root/workflow/image
  code: 7F158B852583394B
wx:
  app-id: wxfdfcef0521a64f52
  app-secret: 149a87770db3129a9bb56f2a8c63f947


